/*
 * Copyright 2022 Korandoru Contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import useSWR from 'swr'
import {RequestedReviewerData} from "../../interfaces";
import {fetcher} from "../../libs/fetcher";
import Head from "next/head";
import Footer from '../../components/footer';
import Loading from '../../components/loading';

export default function RequestedReviewers() {
    const {data} = useSWR<RequestedReviewerData[]>('/api/github/requested_reviewers', fetcher);

    return (
        <div className="flex flex-col items-center justify-center min-h-screen py-2">
            <Head>
                <title>Neptune Dashboard</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className="flex flex-col items-center justify-center w-full flex-1 px-20 text-center">
                <h1 className="text-6xl font-bold">
                    GitHub Requested Reviewers
                </h1>

                {data ? (
                        <table>
                            <thead>
                            <tr>
                                <th>Reviewer</th>
                                <th>Pull Request</th>
                            </tr>
                            </thead>
                            <tbody>
                            {data.map((record) => (
                                <tr key={record.reviewer}>
                                    <td>{record.reviewer}</td>
                                    <td>{record.pr}</td>
                                </tr>
                            ))}
                            </tbody>
                        </table>)
                    : (
                        <Loading/>
                    )
                }
            </main>

            <Footer/>
        </div>
    )
}
