/*
 * Copyright 2022 Korandoru Contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import Head from 'next/head'
import {StarAffinityRatio} from "../../interfaces";
import Footer from "../../components/footer";
import useSWR from 'swr'
import fetch from '../../libs/fetch'

export default function AffinityRatio() {
    const {data} = useSWR<StarAffinityRatio[]>('/api/affinity/ratio', fetch);

    return (
        <div className="flex flex-col items-center justify-center min-h-screen py-2">
            <Head>
                <title>Neptune Dashboard</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className="flex flex-col items-center justify-center w-full flex-1 px-20 text-center">
                <h1 className="text-6xl font-bold">
                    Repository Affinity Ratio
                </h1>

                {data ? (
                        <table>
                            <thead>
                            <tr>
                                <th>RepoName</th>
                                <th>TotalStars</th>
                                <th>OurStars</th>
                                <th>Ratio</th>
                            </tr>
                            </thead>
                            <tbody>
                            {data.map((record) => (
                                <tr key={record.repoName}>
                                    <td>{record.repoName}</td>
                                    <td>{record.totalStars}</td>
                                    <td>{record.ourStars}</td>
                                    <td>{record.ratio}</td>
                                </tr>
                            ))}
                            </tbody>
                        </table>)
                    : (
                        <button type="button" className="bg-indigo-500">
                            <svg className="animate-spin h-5 w-5 mr-3" viewBox="0 0 24 24">
                            </svg>
                            Processing...
                        </button>
                    )
                }
            </main>

            <Footer/>
        </div>
    )
}
