/*
 * Copyright 2022 Korandoru Contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import type {GetServerSideProps, NextPage} from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { getData } from '../libs/useRequest';
import styles from '../styles/Home.module.css'

type Data =   {
    repoName: string,
    totalStars: string,
    ourStars: string,
    ratio: number
}[];

interface Props {
    data: Data
}

const Home = ({ data }: Props) => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Neptune Dashboard</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Neptune Dashboard
                </h1>

                <table>
                    <thead>
                        <tr>
                            <th>RepoName</th>
                            <th>TotalStars</th>
                            <th>OurStars</th>
                            <th>Ratio</th>
                        </tr>
                    </thead>
                    <tbody>
                        {data.map((record) => (
                            <tr key={record.repoName}>
                                <td>{record.repoName}</td>
                                <td>{record.totalStars}</td>
                                <td>{record.ourStars}</td>
                                <td>{record.ratio}</td>
                            </tr>
                        ))}
                    </tbody>
                </table>

            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=korandoru&utm_campaign=oss"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>
                        <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16}/>
                    </span>
                </a>
            </footer>
        </div>
    )
}

export default Home

// This gets called on every request
export const getServerSideProps: GetServerSideProps = async () => {
    const result = await getData("['apache/pulsar,apache/pulsar-site']")
    const data = result.data.map((record: any) => {
        return {
            repoName: record.repo_name,
            totalStars: record.total_stars,
            ourStars: record.our_stars,
            ratio: record.ratio,
        }
    });
    if (!data) return <div>Loading...</div>

    return { props: { data } }
}